//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Registration.h
//  @ Date : 18/03/2021
//  @ Author : RC
//
//


#if !defined(_REGISTRATION_H)
#define _REGISTRATION_H

#include <iostream>
#include "Unit.h"
#include "Result.h"

const unsigned maxNo = 10;

class Registration {

public:

	Registration();

	const unsigned GetCredits();

	const unsigned GetCount();
    void SetCount(unsigned&);

    unsigned long GetStudentId() const;
    void SetStudentId(unsigned long&);

    unsigned GetSemesters() const;
    void SetSemesters(unsigned&);

    void GetRegistrationInfoFromFile(std::ifstream &fileInputToRead);
    void SetRegistrationInfoToFile(std::ofstream &fileOutput);

private:

	unsigned long studentId;
	unsigned semester;
	unsigned count;
	Result results[maxNo]; //array of results
	Units units[maxNo];
};

inline const unsigned Registration::GetCount()
{
    /// PostCondition: return count for the number units
    return count;
}


inline void Registration::SetCount(unsigned& ct)
{
    count = ct;
}

inline unsigned long Registration::GetStudentId() const
{
    /// PostCondition: return studentId
    return studentId;
}

inline void Registration::SetStudentId(unsigned long& id)
{
    studentId = id;
}

inline unsigned int Registration::GetSemesters() const
{
    /// PostCondition: return semester
    return semester;
}

inline void Registration::SetSemesters(unsigned& sems) {

    semester = sems;
}

#endif  //_REGISTRATION_H
