//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Registration.h
//  @ Date : 18/03/2021
//  @ Author : RC
//
//


#if !defined(_REGISTRATION_H)
#define _REGISTRATION_H

#include <iostream>
#include "Unit.h"

const unsigned MaxUnit = 10;

class Registration {
public:
	Registration R();
	const unsigned GetCredits();
	const unsigned GetCount();
	friend std::ostream & operator <<(std::ostream & os, const Registration & R);
	friend std::istream & operator >>(std::istream & is, Registration & R);
private:
	long studentID;
	unsigned semester;
	unsigned count; // number of results
	Unit unit[MaxUnit]; //array of units
};

inline const unsigned Registration::GetCount()
{
  return count;
}

#endif  //_REGISTRATION_H
