//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Unit.h
//  @ Date : 18/03/2021
//  @ Author : RC
//
//

#if !defined(_UNIT_H)
#define _UNIT_H

#include <iostream>
#include <string.h>

class Units {

public:

    Units();

    void SetCredits(unsigned&);
    unsigned int GetCredits() const;

    // ID unit
    void SetID_Unit(std::string&);
    std::string GetIDUnit() const;

    // name
    void SetName(std::string& inputName);
    std::string GetName() const;


    void CleanTheString(std::string& , const std::string& , const std::string& );
    ReArrangeStringWithUnitID(std::string&, std::string&);
    int isCapital(char x);



private:

    std::string name;                 // unit name, C style string. not a C++ string object
    std::string  ID_Unit;       // unit id type integer
    unsigned int  credits;       // number of credits

};


inline void Units::SetCredits(unsigned &creditsInput)
{
    credits = creditsInput;

}

inline unsigned Units::GetCredits() const
{
    /// PostCondition: return credits
    return credits;
}

inline void Units::SetID_Unit(std::string &idUnit)
{
    ID_Unit = idUnit;
}

inline std::string Units::GetIDUnit() const
{
    /// PostCondition: return ID_Unit
    return ID_Unit;
}

inline void Units::SetName(std::string& inputName){

    name = inputName;
}

inline std::string Units::GetName() const
{
    /// PostCondition: return name
    return name;
}
#endif  //_UNIT_H
