//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Unit.h
//  @ Date : 18/03/2021
//  @ Author : RC
//
//

#if !defined(_UNIT_H)
#define _UNIT_H

#include <iostream>
#include <string.h>

const unsigned UnitNameSize = 10;
const unsigned uId = 6;

class Unit {
public:
	Unit();
	Unit(char * unitName, char * unitID, unsigned cred);
	const char * GetUnitName();
	const char * GetUnitID();
	const unsigned GetCredits();
	void SetUnitName(char * name);
	void SetUnitID(char * id);
	void SetCredits(unsigned cred);
	friend std::ostream & operator <<(std::ostream & os, const Unit & unit);
	friend std::istream & operator >>(std::istream & is, Unit & unit);
private:
	char uName[UnitNameSize];
	char uID[uId];
	int credits;
};

inline const unsigned Unit::GetCredits()
{
  return credits;
}

inline void Unit::SetCredits( unsigned cred )
{
  credits = cred;
}

#endif  //_UNIT_H
