//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Unit.cpp
//  @ Date : 18/03/2021
//  @ Author : RC
//

// Includes

#include "Unit.h"

Units::Units() = default;

void Units::CleanTheString(std::string& inputStr, const std::string &thisStr, const std::string &toBeReplaced)
{

    unsigned long pos=0;

    unsigned long thisStrLen = thisStr.length();
    unsigned long replacingStrLen = toBeReplaced.length();

//    for(unsigned i=0; i < inputStr.length(); i++){
//        if(isCapital(inputStr[i]))
//        {
//            inputStr.append(inputStr, i, 1);
//
//        }
//    }

    while((pos = inputStr.find(toBeReplaced, pos)) != -1)
    {
        inputStr.replace(pos, replacingStrLen, thisStr);
        // increment the position replaced
        pos += thisStrLen;
    }

}


Units::ReArrangeStringWithUnitID(std::string& name, std::string& unitId)
{

    std::string alteredUnitName;
    std::string alteredUnitID;

    alteredUnitID = name.substr(0,3) + unitId;
    alteredUnitName = name.substr(4, name.length() -1);

    unitId = alteredUnitID;
    name = alteredUnitName;

}

// Unfinished
int Units::isCapital(char x)
{
    if (x >='A' && x <= 'Z'){
        return 1;
    } else {
        return 0;
    }
}
