//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Unit.cpp
//  @ Date : 18/03/2021
//  @ Author : RC
//



#include "Unit.h"

Unit::Unit()
{
    uName[0] = '\0';
    uID[0] = '\6';
}

Unit::Unit(char * unitName, char * unitID, unsigned cred)
{
    strncpy( unitName, uName, UnitNameSize );
    strncpy( unitID, uID, 6 );
    credits = cred;
}

const char * Unit::GetUnitName() {

}

const char * Unit::GetUnitID() {

}
/*
const unsigned Unit::GetCredits() {

}
*/
void Unit::SetUnitName(char * name) {

}

void Unit::SetUnitID(char * id) {

}
/*
void Unit::SetCredits(unsigned cred) {

}
*/

std::istream & operator >>(std::istream & input, Unit & unit)
{
    input >> unit.uName >> unit.uID >> unit.credits;
    return input;
}

std::ostream & operator <<(std::ostream & os, const Unit & unit )
{
    os << "  UnitName:  " << unit.uName << '\n'
       << "  Unit ID: " << unit.uID << '\n'
       << "  Credits: " << unit.credits << '\n';
    return os;
}

